[package]
name = "math_multiplication_trainer"
version = "0.3.1"
edition = "2021"
authors = ["EvgenHi"]
readme = "README.md"
repository = "https://github.com/EvgenHi/math_multiplication_trainer"
license = "MIT"

[dependencies]
eframe = "0.19.*"
rand = "0.8.*"
soloud = "1.*.*"
